### ISSUE TITLE
I've got an issue with you

### ISSUE THREAD

**Issue by Pantonius** [donatienLeray/bmofetch#2]
Heute, 20 Uhr, hinter dem ZT-Gebäude, ohne Haare ziehen!

**Comment by tuxerator** [comment]
20€ auf Dodo

**Comment by donatienLeray** [comment]
Das Wetter ist zu schlecht für einen Kampf draußen. 🌧️

**Comment by donatienLeray** [comment]
Das Wetter ist zu schlecht für einen Kampf draußen. 🌧️
