### ISSUE TITLE
Working Directory

### ISSUE THREAD

**Issue by Pantonius** [donatienLeray/bmofetch#3]
To use bmofetch with my nix config it would be nice to allow for a working directory outside of the git repo in terms of `bmofetch.conf` and `bmo.txt`. (the nix-store is read-only, so writes are not allowed).

Maybe a new parameter for `bmo.txt` such that I can change the working directory.

Love,
Anton :heart:

**Comment by donatienLeray** [comment]
When using [bmosay](https://github.com/donatienLeray/bmofetch#bmosay) you can now use `-p` to specify the path to your working directory. Note that the path must be given directly after the flag and must contain [`bmofetch.conf`](https://github.com/donatienLeray/bmofetch/blob/main/bmofetch.conf) and [`bmofetch.txt`](https://github.com/donatienLeray/bmofetch/blob/main/bmo.txt).

**Examples:**
```bash
./bmosay.sh -p ~/.config/neofetch/bmofetch "Hello World!"
./bmosay.sh -qr -p ~/.config/neofetch/bmofetch ~/quotes.txt
./bmosay.sh  --path ~/.config/neofetch/bmofetch -r ~/quotes.txt
```
