### ISSUE TITLE
Auto-copy on -p

### ISSUE THREAD

**Issue by Pantonius** [donatienLeray/bmofetch#4]
It would be nice for bmofetch to recognize if the chosen working directory does not include the necessary files and copy them over.

**Comment by donatienLeray** [comment]
When using [`bmosay`](https://github.com/donatienLeray/bmofetch#bmosay) `-p <dir>` to specify the path to your working directory, if [`bmofetch.conf`](https://github.com/donatienLeray/bmofetch/blob/main/bmofetch.conf) or [`bmofetch.txt`](https://github.com/donatienLeray/bmofetch/blob/main/bmo.txt) are not in it, you will be asked it you would like to copy them from the directory you called `bmosay` from if they are in there.

**Example:**
```console
foo@bar:~$ ./scripts/bmosay.sh -p ~/test "Hello World!"
File 'bmo.txt' not found in directory 'test/'. Do you want to copy it from '/home/foo/scripts'? [Y/n]: y
Success: File 'bmo.txt' copied to directory 'test/'.
Success: BMO now says "Hello World!"
```
